### ISSUE TITLE
Support runtime connection and disconnection of Stream Decks (hotplugging)

### ISSUE THREAD

**Issue by Lange** [Lange/node-elgato-stream-deck#14]
Right now, this library throws an error on startup if you don't have a Stream Deck connected. Likewise, if you disconnect and reconnect your Stream Deck, you must restart the library.

This is pretty bad. We should add support for automatically detecting when a Stream Deck is connected.

**Comment by farfabet** [comment]
I made a fix proposal but cannot test it as I don't own a stream deck, let me know if you want me to request a pull : 
https://github.com/farfabet/node-elgato-stream-deck/commit/16c2d71414e2f634f2ec1bba3195dca9cf6bd664

**Comment by Lange** [comment]
Thanks @farfabet!

We want to try to avoid polling-based systems because of the performance impacts and the potential for issues to arise. For example, I've had cases where frequently enumerating the list of USB devices on Windows can cause USB audio devices to crackle.

[`node-usb-detection`](https://github.com/MadLittleMods/node-usb-detection) seems like it might be just what we need. It could handle detecting the insertion and removal of devices, while we let `node-hid` do the actual communicating.

(Sidenote: we probably don't actually need `node-usb-detection` to detect removals, because `node-hid` almost certainly emits an `error` event when this happens already. We really just need the insertion events from `node-usb-detection`.)

**Comment by farfabet** [comment]
I totally understand, I searched for such solution in `node-hid` and went with polling by default. Anyway I'm really interested in what you did with `nodecg `and will keep an eye on this project to. :)

**Comment by Julusian** [comment]
The library has changed a lot since this was opened. It does not support multiple devices, and there is an [example](https://github.com/Lange/node-elgato-stream-deck/blob/master/examples/device-detection.js) showing how simple it is to do device detection with [usb-detection](https://github.com/MadLittleMods/node-usb-detection), so I don't think there is anything more we should do here.

Feel free to open a new issue if you think there is more this library should provide to help with this
