### ISSUE TITLE
Should we adopt a type system?

### ISSUE THREAD

**Issue by Lange** [Lange/node-elgato-stream-deck#25]
I've never used a JavaScript type system and I kind of want to use this project as an excuse to do so. The codebase is small, it'll be easy.

Our options are [TypeScript](https://www.typescriptlang.org/) or [Flow](https://flow.org/). I'm personally leaning towards Flow. It seems better at catching programmer errors by default. And, selfishly, I want to evaluate Flow's usage for NodeCG where I don't think I want to use TypeScript for an array of reasons I don't need to get into here.

Thoughts?

**Comment by Lange** [comment]
Another strong plus for Flow is the amazing [`flow-jsdoc`](https://github.com/Kegsay/flow-jsdoc). This would let us get full type checking more or less for free, without cluttering up our code. We're going to have JSDoc comments either way (and we already do thanks to #24!), may as well make them work for us.

**Comment by ProbablePrime** [comment]
I'm bias:
- Have you seen http://typedoc.org/ ?
- Typescript is great at catching programming errors.
- The default config file lets a lot of errors through but: https://github.com/ProbablePrime/typescript-boilerplate/blob/master/tsconfig.json is just about the strictest i've seen.
- All of this Plus TSLint and we get everything we dont have.

**Comment by ProbablePrime** [comment]
I also don't like the compile setup here: https://flow.org/en/docs/install/ 

`tsc` from typescript compiles directly all the way down to ES3

**Comment by Lange** [comment]
Kk, I suppose I'm sold. It does make sense that we should use the tool that at least one of us knows.

Would you be willing to set up the configuration and boilerplate for Typescript and then let me take a crack at implementing it? I'd like to learn it so that I may experiment with it in NodeCG. Thanks!

**Comment by danieltian** [comment]
Just throwing in my 2 cents, I'm not a big fan of typed Javascript for the following reasons:

1. They all have to transpile down to plain Javascript anyway. This doesn't matter so much when you're using TypeScript in your own project, but it matters a lot when you're using a npm module that uses TypeScript, because the consumer of your project now has to deal with transpiled code.

2. There are already good tools such as `jshint` and `eslint` that support a pseudo-compile time check that will catch a lot of the more common JS mistakes.

3. Everyone who uses Node knows JavaScript. Not everybody knows TypeScript and/or Flow. Having to ramp up on a similar, yet slightly different syntax has its associated costs.

4. Unlike other typed languages, JavaScript really only has 5 types: objects, strings, numbers, arrays, and functions. This makes them incredibly easy to use, and also easy to reason about. Once you start adding strong typing, it significantly complicates things and forces you to start using interfaces if you want to do testing with mock objects, for example.

5. Strong typing removes one of the key advantages of JS: the ability to freely manipulate objects as you see fit. Take for example this C# code, which customizes the format the JSON.Net uses to spit out JSON:

https://github.com/danieltian/openhardwaremonitor-json-server/blob/master/OpenHardwareMonitorJsonServer/Program.cs#L12-L84

I have to implement `IVisitor` and create sub-classes for `JsonConverter` and `DefaultContractResolver` and override the default methods, just so that I can serialize an object tree and remove two keys from each object. If this was JS instead, I could've just used the `js-deep-for-each` library and do this:

```js
deepForEach(objectTree, (value, prop, subject, path) => {
  if (prop == 'Values' || prop == 'Parameters') {
    delete subject[prop];
  }
});
```

**Comment by ProbablePrime** [comment]
For typescript: 
De-serializing JSON is quite easy, Ultimately you can just use `any` or something like  [IJSON](https://github.com/WatchBeam/bORM/blob/37ae1aeaa13ab684e294086cc235ec377d9e8f80/src/Types.ts#L604)

Its a lot better usually to use interfaces though as you can document every property at which point you get self documenting code.

**Comment by ProbablePrime** [comment]
Probably best to try and tackle this after: #27

**Comment by Lange** [comment]
This is an interesting blog post on the topic: https://medium.com/the-thinkmill/adopting-flow-typescript-3549a3a36d51

**Comment by ProbablePrime** [comment]
I think that article misses a point.
>>>
Flow only requires us to type the exports of a file and the external modules. Everything else can be inferred.

This is a bad idea, one of the points of using typescript is to get code that works and lets you sleep both internally and externally. 

Developers can't use internal modules and values incorrectly and their code self documents itself as they write it.

Using typings on just external facing components seem to suggest that the author is treating type systems as a validation tool and not a code quality tool.

Regardless of type system external libraries and implementers can then choose to use our typings or use the module within regular node. 

The majority of work I do in typescript leads to modules that are fully compatible with Typescript, Node and Browsers. Of the people using it from Node its my understanding that regardless of the type system they'd lack this protection.

>>>
There are no errors because TypeScript requires that we type annotate our function before it will check the type like this

As they say noImplictAny fixes this. You can configure this in a tsconfig file. I usually use a file config based on the one in use at Mixer. [Its incredibly strict](https://github.com/ProbablePrime/typescript-boilerplate/blob/master/tsconfig.json#L8). This combined with a tslint is likely to initially drive you insane but it leads to code that just works.

As for speed, this is a rather small library at present so the graphs don't really apply here.

**Comment by Lange** [comment]
After giving this some space, I'm okay with using TypeScript. I'd be happy to accept a PR which converts this to a TS package.

**Comment by Lange** [comment]
@ProbablePrime Would you be willing to start a branch which adds your preferred TypeScript & TSLint configurations? From there, myself or another contributor can do the rest of the conversion, if you are time-limited.

**Comment by ProbablePrime** [comment]
@Lange Sorting it out now :)

**Comment by ProbablePrime** [comment]
branch created: `feat/typescript`.

Notes:
- Swapped ESlint for Tslint using https://github.com/xojs/tslint-xo ruleset. Seems to match JS XO
- TSLint is very unhappy with the current code base
- Typescript is also unhappy this is because I usually run typescript in strict mode. This is very militaristic but it makes for better code in the long run. 
- I have no idea if AVA tests or coverage will work we need to fix tslint and typescript complaining before we get there. Some short googles say that they should work though
- I left the old typings file in the root, it might help whilst its re-written. Remove it when done though. Typings get automatically generated
- module now lives in `src` and compiles to `lib`, package.json updated to point there. Same with the examples
- I dont have a streamdeck with me at the moment. I can borrow one from a colleague should we need some support.
- If any of our dependancies use default exports we might have issues importing them using typescript import statements. In this case use require and use tslint-disable comments to prevent the errors.

Worflow:
- Only edit files in src/
- run npm run build to compile
- If you use visual studio code grab the tslint and typescript hero extensions. everything else is supported out of the box

@Lange There you go, Please please ask questions. Im unable to 100% ensure that our toolchain works whilst the early portions of it error out :)

**Comment by ProbablePrime** [comment]
nyc coverage data running here on a module from work: https://github.com/mixer/etcd3/blob/master/package.json

**Comment by Lange** [comment]
Thanks @ProbablePrime! I've been using TS in some other projects lately so I have at least a basic literacy in it.

I'm unsure when exactly I'll get around to re-writing this module as TS, but that branch provides a perfect starting point.

**Comment by Julusian** [comment]
This repo is now all done in typescript
