### ISSUE TITLE
fillImageFromFile in 3.0

### ISSUE THREAD

**Issue by zorkhan** [Lange/node-elgato-stream-deck#67]
Has this been removed? I see some comments stating that node.js 7.6 or higher is required. I am running v8.16.0.

**Comment by Julusian** [comment]
Yes, this has been removed.
The reason is that it required a dependency that was an unnecessary burden for a lot of users as it was large and makes installation more complex on some systems.
The readme gives an example of how to achieve the same thing yourself, so hopefully this will be sufficient for you. https://github.com/Lange/node-elgato-stream-deck#example-2
