### ISSUE TITLE
process not exiting

### ISSUE THREAD

**Issue by jaredgudnason** [Lange/node-elgato-stream-deck#71]
Hi,
not a huge developer, just tinkering, but have narrowed down the issue to the stream deck library.

whenever i have a js file with a streamdeck library, the code will not exit by itself.  however, if i put a process.exit() at the end, it cuts off the process of filling the buffer.  Any guidance would be appreciated.

here is entire code, making a text label.  Runs fine, does everything, but doesn't exit.

var txt2png = require('text2png');
const sd = require('elgato-stream-deck')

const streamDeck = sd.openStreamDeck()
const sharp = require('sharp')
const path = require('path');
sharp(txt2png('Text Button', {
  font: '30px Tahoma',
  color: 'teal',
  backgroundColor: 'linen',
  lineSpacing: 1,
  padding: 10
})	
 )
	.flatten() // Eliminate alpha channel, if any.
	.resize(streamDeck.ICON_SIZE, streamDeck.ICON_SIZE,{fit:"contain"}) // Scale up/down to the right size, cropping if necessary.
	.raw() // Give us uncompressed RGB.
	.toBuffer()
	.then(buffer => { streamDeck.fillImage(2, buffer) })
	.catch(err => {	console.error(err)})

**Comment by Lange** [comment]
The process not exiting is intentional, because `elgato-stream-deck` is meant for long-running systems and it has to keep things such as the USB connection open.

If you'd like your script to exit after it has finished its work, you'll need to wait for your Promise chain to resolve, and _then_ call `process.exit`. Here's an example to get you started. It might not work right off the bat because I haven't tested it, but it should give you an idea to further tinker with:

```js
var txt2png = require('text2png');
const sd = require('elgato-stream-deck')

const streamDeck = sd.openStreamDeck()
const sharp = require('sharp')
const path = require('path');
sharp(
	txt2png('Text Button', {
		font: '30px Tahoma',
		color: 'teal',
		backgroundColor: 'linen',
		lineSpacing: 1,
		padding: 10
	})
)
	.flatten() // Eliminate alpha channel, if any.
	.resize(streamDeck.ICON_SIZE, streamDeck.ICON_SIZE,{fit:"contain"}) // Scale up/down to the right size, cropping if necessary.
	.raw() // Give us uncompressed RGB.
	.toBuffer()
	.then(buffer => {
		streamDeck.fillImage(2, buffer)
		process.exit(0);
	})
	.catch(err => { console.error(err)})
```

**Comment by jaredgudnason** [comment]
ahh thanks for that..
i'm now reading about promise chains and async issues.. interesting.
i was planning on nesting that entire chunk into a function like
"updateButton" so i could then update a bunch of buttons.
any way i could do that, and only exit when the entire promise chain is
done?
(sorry for noob type questions, i'm googling lots here.  ;)

**Comment by Lange** [comment]
Yep, you can throw a `.then` on the end of any promise chain at any time, pretty much. You can also use `async/await` if you find using `.then` to be ugly. At this point, since you know what you want is possible, I'm going to close this issue and encourage you to read up on places like MDN and the Google developer site, which can provide more info on these fundamentals than I ever could.

**Comment by jaredgudnason** [comment]
you betcha.  Thank you for the prompt reply.
I'll get it figured.
