### ISSUE TITLE
Is it possible to switch / select a profile?

### ISSUE THREAD

**Issue by freps** [Lange/node-elgato-stream-deck#87]
Hey all,
I started to use the library to enhance the usability of an application and it already feels pretty good! 

To optimize it even more: Is there a way to detect which profile is currently displayed or to switch to another profile? I want to switch to an empty profile to avoid conflicts with existing buttons when it starts up, and go back to the default profile when the application is shutting down. Is this possible?

**Comment by Julusian** [comment]
I think you have misunderstood how this library works and is supposed to be used.

The elgato application should not be running at the same time as using this library, as otherwise there will be conflicts as we access the usb device directly.
As such there is no knowledge, awareness or control of any 'profiles'

**Comment by freps** [comment]
I have interpreted the sentences "_please note that node-elgato-stream-deck is NOT a standalone application. It is not something you download and run on its own. It is not an alternative to the official Stream Deck program provided by Elgato._" to mean that the elgato software must run in the background to operate. But thanks for clarification.
